name: Sync Fork and Apply Patch

on:
  schedule:
    # Run every hour to check for upstream changes
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering
  
jobs:
  sync-and-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/PoeticRainbow/golden-days.git
          git fetch upstream
          
      - name: Check for commit newer than last run
        id: check
        run: |
          echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Apply patch
        if: steps.check.outputs.changes == 'true'
        run: |
          chmod +x ./patch.sh
          ./patch.sh
          
      - name: Create artifact
        if: steps.check.outputs.changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: golden-days-patched-${{ github.run_number }}
          path: .
